apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflare
type: Opaque
data:
    token: ENC[AES256_GCM,data:O3l/l0pWGz6LH4EF+J1muxQ9Df98nSbje/q/AcHmxZ/TsZxVn6CdOIBVoZpBB9/AhlTiWAIgNha4uD9vAxwdA5Lk9zIH9I+PbeZSi2LoJ5rgDBKQxb7ECcz4HLbAYmpZvso8NdtXL/QqKlgYGggNb7zqiWsLxmSUTRMxmU0aG62yh/kA7rdso/JOg994lPut7xO7Zm0f8c2wK5f+BtBm3iV96FrXU3tjojrY0nv4WkCIQNP93xEgm9/w/Rh9fUDYnRDLxucLWnbtIeaPV1ZPJK9w6SXHu1Juy6ryGYUUrK9brPeYk2uki3bd8qOchB1DvD4ONfFh3hs=,iv:2eeWuyR7InDK161ikjjDr1Ycrh7j4TI9gj/RYHKMb1w=,tag:29Tc+uW8RcEhSy9D9a2PCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdE9kaitkeGFNU0g1ZXJ0
            a3BNYXBxVTZLV0p4UnQzT3cvQjhidnZhK0ZVCm5qc2l4V25BVE9SYkJERmtNVzZr
            bmdtaURJc04ycFAzQWoraEw2VE1objAKLS0tIHROdStxOXpaVUlCdUZqR2pML2ov
            dlJBYTZ3aXNqNkdSWHJkNlBxa3lndkkKqTVvACU6Y1QzV23DApf31UHik44brdZm
            E9is8ElaT0I/ViLA65f/bZHVVV5CtuYpslDKE4ENLmuZmUrPJp2Ekg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18k59jeka6qm0nkm8ckl4wd52z3v8l4wmqshshkj44qe7ylacqqysav9zj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:57:00Z"
    mac: ENC[AES256_GCM,data:8kuCVPk/Pid5gBseKr7FLbinp2cFUrVe6fveYNM5ZZBI6zCA2GCWtaE3oG/hjZ9X8nGJWVHHkjflgHPgYoaihMJoB2Px26xuEtitpeCRBbuHFPqFX8EK/eGqNyDfWpq+wMN4T48Vs8NRkT5HPWsLWsybNLwfL3nhVwndSB4FvaA=,iv:xSNHrKPMFk/Vft1A2PNeCSAaG3rzW/qVFOGxC5Sswrs=,tag:Wi21zrs++wZ64F3tFgJBxw==,type:str]
    version: 3.13.3
