apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-production
resources:
  - namespace.yaml
  - ../base
images:
  - name: ghcr.io/0b-ivan/kernel-notes-blog
    newTag: 68e15a1d56fcdd8b3b286da2d2f81d650e61f749
  - name: ghcr.io/0b-ivan/kernel-notes-search
    newTag: 68e15a1d56fcdd8b3b286da2d2f81d650e61f749
  - name: ghcr.io/0b-ivan/kernel-notes-status
    newTag: 68e15a1d56fcdd8b3b286da2d2f81d650e61f749
replicas:
  - name: blog
    count: 3

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: search
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
