apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog-production
resources:
  - namespace.yaml
  - ../base
images:
  - name: ghcr.io/0b-ivan/kernel-notes-blog
    newTag: a0ba014de0335a87722eed5d09af826f4dcb7d41
  - name: ghcr.io/0b-ivan/kernel-notes-search
    newTag: a0ba014de0335a87722eed5d09af826f4dcb7d41
  - name: ghcr.io/0b-ivan/kernel-notes-status
    newTag: 7806d419b019ec0ff1721eea9a7fd3dede094fee
replicas:
  - name: blog
    count: 3

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: search
    patch: |-
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 0
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
