apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: blog-to-search-delay-500ms-measured
  namespace: blog-staging
  labels:
    chaos.obivan.org/experiment: network-delay
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - blog-staging
    labelSelectors:
      app: blog
      chaos.obivan.org/enabled: "true"
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - blog-staging
      labelSelectors:
        app: search
        chaos.obivan.org/enabled: "true"
  delay:
    latency: "500ms"
    correlation: "0"
    jitter: "0ms"
  duration: "30s"
