apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog.yaml
  - app
  - cloudflared.yaml
  - chaos-monkey.yaml
  - chaos-mesh.yaml
  - production-flux.yaml
  - secrets/ghcr-pull.sops.yaml
  - secrets/cloudflared-token.sops.yaml
images:
  - name: cloudflare/cloudflared
    newTag: 2026.9.1
  - name: ghcr.io/0b-ivan/kernel-notes-blog
    newTag: 619ef7e30d95599c9fce5f77bd6f2fed3796fa03
  - name: ghcr.io/0b-ivan/kernel-notes-search
    newTag: 619ef7e30d95599c9fce5f77bd6f2fed3796fa03
  - name: ghcr.io/0b-ivan/kernel-notes-status
    newTag: 619ef7e30d95599c9fce5f77bd6f2fed3796fa03
  - name: ghcr.io/0b-ivan/kernel-notes-chaos
    newTag: 619ef7e30d95599c9fce5f77bd6f2fed3796fa03
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: blog
      namespace: blog-staging
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - staging-server.js
      - op: add
        path: /spec/template/metadata/labels/chaos.obivan.org~1enabled
        value: "true"
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: search
      namespace: blog-staging
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/chaos.obivan.org~1enabled
        value: "true"

