apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog.yaml
  - cloudflared.yaml
  - secrets/ghcr-pull.sops.yaml
  - secrets/cloudflared-token.sops.yaml
images:
  - name: cloudflare/cloudflared
    newTag: 2026.9.1
  - name: ghcr.io/0b-ivan/kernel-notes-blog
    newTag: dd1cf1820f0540e86c7dcd73ffda4bb2b612d2c3
  - name: ghcr.io/0b-ivan/kernel-notes-search
    newTag: dd1cf1820f0540e86c7dcd73ffda4bb2b612d2c3
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: blog
      namespace: blog-staging
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args
        value:
          - staging-server.js
